#!/bin/bash
#
# Situation Room Agent Installer
# One-liner: curl -sSL https://vault.stormycloud.org/agent/install.sh | sudo bash
#

set -e

# Configuration
SERVER_URL="wss://vault.stormycloud.org/api/monitoring/ws/agent"
API_KEY="EDWmncsWveEL61JXe1WD_WFLHeuGMdknJSxqP2eKN6U"
INSTALL_DIR="/opt/situation-room-agent"
CONFIG_DIR="/etc/situation-room"
AGENT_URL="https://vault.stormycloud.org/agent/situation-room-agent.py"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    log_error "Cannot detect OS"
    exit 1
fi

log_info "Detected OS: $OS"
log_info "Installing Situation Room Agent..."

# Install Python and pip if needed
install_python() {
    case $OS in
        ubuntu|debian)
            apt-get update -qq
            apt-get install -y -qq python3 python3-pip python3-venv curl > /dev/null
            ;;
        centos|rhel|fedora|rocky|almalinux)
            if command -v dnf &> /dev/null; then
                dnf install -y -q python3 python3-pip curl
            else
                yum install -y -q python3 python3-pip curl
            fi
            ;;
        arch|manjaro)
            pacman -Sy --noconfirm python python-pip curl > /dev/null
            ;;
        *)
            log_warn "Unknown OS, assuming Python3 is installed"
            ;;
    esac
}

# Check for Python
if ! command -v python3 &> /dev/null; then
    log_info "Installing Python3..."
    install_python
fi

# Create directories
log_info "Creating directories..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"

# Create virtual environment
log_info "Setting up Python virtual environment..."
python3 -m venv "$INSTALL_DIR/venv"
source "$INSTALL_DIR/venv/bin/activate"

# Install dependencies
log_info "Installing Python dependencies..."
pip install --quiet --upgrade pip
pip install --quiet websockets pyyaml httpx dnspython

# Download agent script
log_info "Downloading agent script..."
curl -sSL "$AGENT_URL" -o "$INSTALL_DIR/situation-room-agent.py"
chmod +x "$INSTALL_DIR/situation-room-agent.py"

# Get hostname
HOSTNAME=$(hostname)

# Create configuration
log_info "Creating configuration..."
cat > "$CONFIG_DIR/agent.yml" << EOF
# Situation Room Agent Configuration
# Generated by installer on $(date)

server:
  url: "$SERVER_URL"
  api_key: "$API_KEY"
  verify_ssl: true

agent:
  hostname: "$HOSTNAME"
  report_interval_seconds: 60

ufw:
  enabled: true
  log_path: /var/log/ufw.log

health_checks:
  enabled: true
  checks:
    - name: disk_root
      type: disk
      path: /
    - name: memory
      type: memory
    - name: load
      type: load
    - name: internet
      type: connectivity
      host: 8.8.8.8
      port: 53

# Auto-update configuration
auto_update:
  enabled: true
  version_url: "https://vault.stormycloud.org/agent/version"
  install_dir: "$INSTALL_DIR"
  venv_path: "$INSTALL_DIR/venv"
  service_name: "situation-room-agent"
EOF

chmod 600 "$CONFIG_DIR/agent.yml"

# Create systemd service
log_info "Creating systemd service..."
cat > /etc/systemd/system/situation-room-agent.service << EOF
[Unit]
Description=Situation Room Monitoring Agent
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=$INSTALL_DIR/venv/bin/python $INSTALL_DIR/situation-room-agent.py --config $CONFIG_DIR/agent.yml
Restart=always
RestartSec=10

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadOnlyPaths=/
ReadWritePaths=/var/log $INSTALL_DIR

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd and start service
log_info "Starting service..."
systemctl daemon-reload
systemctl enable situation-room-agent
# Use restart to ensure the new version runs (handles both fresh install and updates)
systemctl restart situation-room-agent

# Check status
sleep 2
if systemctl is-active --quiet situation-room-agent; then
    log_info "Agent installed and running successfully!"
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}  Situation Room Agent Installed!${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo "  Hostname:  $HOSTNAME"
    echo "  Server:    $SERVER_URL"
    echo "  Config:    $CONFIG_DIR/agent.yml"
    echo ""
    echo "  Useful commands:"
    echo "    Status:  systemctl status situation-room-agent"
    echo "    Logs:    journalctl -u situation-room-agent -f"
    echo "    Restart: systemctl restart situation-room-agent"
    echo "    Stop:    systemctl stop situation-room-agent"
    echo ""
else
    log_error "Service failed to start. Check logs with:"
    echo "  journalctl -u situation-room-agent -n 50"
    exit 1
fi
